// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	config_v1 "github.com/sjenning/api/config/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFeatures implements FeatureInterface
type FakeFeatures struct {
	Fake *FakeConfigV1
}

var featuresResource = schema.GroupVersionResource{Group: "config.openshift.io", Version: "v1", Resource: "features"}

var featuresKind = schema.GroupVersionKind{Group: "config.openshift.io", Version: "v1", Kind: "Feature"}

// Get takes name of the feature, and returns the corresponding feature object, and an error if there is any.
func (c *FakeFeatures) Get(name string, options v1.GetOptions) (result *config_v1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(featuresResource, name), &config_v1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*config_v1.Feature), err
}

// List takes label and field selectors, and returns the list of Features that match those selectors.
func (c *FakeFeatures) List(opts v1.ListOptions) (result *config_v1.FeatureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(featuresResource, featuresKind, opts), &config_v1.FeatureList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &config_v1.FeatureList{ListMeta: obj.(*config_v1.FeatureList).ListMeta}
	for _, item := range obj.(*config_v1.FeatureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested features.
func (c *FakeFeatures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(featuresResource, opts))
}

// Create takes the representation of a feature and creates it.  Returns the server's representation of the feature, and an error, if there is any.
func (c *FakeFeatures) Create(feature *config_v1.Feature) (result *config_v1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(featuresResource, feature), &config_v1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*config_v1.Feature), err
}

// Update takes the representation of a feature and updates it. Returns the server's representation of the feature, and an error, if there is any.
func (c *FakeFeatures) Update(feature *config_v1.Feature) (result *config_v1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(featuresResource, feature), &config_v1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*config_v1.Feature), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFeatures) UpdateStatus(feature *config_v1.Feature) (*config_v1.Feature, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(featuresResource, "status", feature), &config_v1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*config_v1.Feature), err
}

// Delete takes name of the feature and deletes it. Returns an error if one occurs.
func (c *FakeFeatures) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(featuresResource, name), &config_v1.Feature{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFeatures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(featuresResource, listOptions)

	_, err := c.Fake.Invokes(action, &config_v1.FeatureList{})
	return err
}

// Patch applies the patch and returns the patched feature.
func (c *FakeFeatures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *config_v1.Feature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(featuresResource, name, data, subresources...), &config_v1.Feature{})
	if obj == nil {
		return nil, err
	}
	return obj.(*config_v1.Feature), err
}
